# Generated by Django 2.1.2 on 2018-10-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GdsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GdsImg', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('GdsCat', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.Categoryes')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
