# Generated by Django 2.1.2 on 2018-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryes',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='gdsmodel',
            name='GdsCat',
        ),
        migrations.AddField(
            model_name='gdsmodel',
            name='GdsCat',
            field=models.ManyToManyField(to='post.Categoryes'),
        ),
    ]
