# Generated by Django 2.0.7 on 2018-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdsmodel',
            name='name',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='img'),
        ),
    ]
