# Generated by Django 2.0.7 on 2018-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_gdsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsmodel',
            name='name',
            field=models.FileField(blank=True, upload_to='static/img', verbose_name='img'),
        ),
    ]
