# Generated by Django 2.1.2 on 2018-10-31 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181031_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='gdsmodel',
            name='GdsCat',
        ),
        migrations.DeleteModel(
            name='Categoryes',
        ),
        migrations.AddField(
            model_name='gdsmodel',
            name='GdsCat',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
        ),
    ]
