# Generated by Django 2.1.2 on 2018-10-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181031_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsmodel',
            name='GdsCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
        ),
    ]
