# Generated by Django 2.0.7 on 2018-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180808_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsmodel',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
