# Generated by Django 2.0.7 on 2018-08-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180808_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdsmodel',
            old_name='name',
            new_name='GdsImg',
        ),
    ]
