# Generated by Django 2.1 on 2018-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180808_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
