# Generated by Django 2.1 on 2018-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180814_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdsmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
