# Generated by Django 2.1 on 2018-08-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_gdsmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdsmodel',
            options={'ordering': ['date']},
        ),
    ]
